# Generated by Django 3.2.4 on 2021-07-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='image',
        ),
    ]
