# Generated by Django 3.2.4 on 2021-07-12 21:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_content',
            field=wagtail.core.fields.StreamField([('subheading', wagtail.core.blocks.RichTextBlock())], null=True),
        ),
    ]
