# Generated by Django 3.2.4 on 2021-06-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecarouselimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
    ]
