# Generated by Django 3.2.4 on 2021-06-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_banner_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
    ]
