# Generated by Django 3.2.4 on 2021-06-16 14:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_content',
            field=wagtail.core.fields.StreamField([('subheading', wagtail.core.blocks.RichTextBlock(features=['h2'], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['p', 'link', 'bold', 'italic'], icon='pilcrow')), ('second_paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow'))], null=True),
        ),
    ]
