# Generated by Django 3.2.4 on 2021-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='Instagram',
            new_name='instagram',
        ),
    ]
